-- 코드를 입력하세요
WITH SALE AS (SELECT BOOK_ID,SUM(SALES) AS SALES_SUM FROM BOOK_SALES WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31' GROUP BY BOOK_ID),
BOOK AS (SELECT BOOK_ID,CATEGORY,B.AUTHOR_ID,A.AUTHOR_NAME,PRICE FROM BOOK B LEFT JOIN AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID)

# SELECT B.AUTHOR_ID,AUTHOR_NAME,CATEGORY, (PRICE*S.SALES_SUM) AS TOTAL_SALES
# FROM BOOK B LEFT JOIN SALE S ON B.BOOK_ID=S.BOOK_ID
# ORDER BY B.AUTHOR_ID, CATEGORY DESC

# SELECT BOOK_ID,SUM(SALES) AS SALES_SUM FROM BOOK_SALES WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31' GROUP BY BOOK_ID
# SELECT BOOK_ID,SALES  FROM BOOK_SALES WHERE BOOK_ID=1 AND SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'# GROUP BY BOOK_ID
# SELECT BOOK_ID,CATEGORY,B.AUTHOR_ID,A.AUTHOR_NAME,PRICE FROM BOOK B LEFT JOIN AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID

SELECT B.AUTHOR_ID,AUTHOR_NAME,CATEGORY, SUM(PRICE*S.SALES_SUM) AS TOTAL_SALES
FROM BOOK B LEFT JOIN SALE S ON B.BOOK_ID=S.BOOK_ID
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY B.AUTHOR_ID ASC, CATEGORY DESC
