with A as (
SELECT CAR_ID, START_DATE, END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '2022-11-30'>= START_DATE AND END_DATE >='2022-11-01'
),
B as (
SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID,car_type,daily_fee
FROM CAR_RENTAL_COMPANY_CAR LEFT JOIN A on CAR_RENTAL_COMPANY_CAR.CAR_ID=A.CAR_ID
WHERE A.CAR_ID is NULL and CAR_TYPE in ('SUV','세단')
),
C as (
SELECT CAR_TYPE,DURATION_TYPE,DISCOUNT_RATE    
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE TRIM(TRAILING '일 이상' FROM DURATION_TYPE)='30'
)

# SELECT *
# FROM A
# ORDER BY CAR_ID

# SELECT CAR_ID,B.CAR_TYPE,daily_fee,DURATION_TYPE,DISCOUNT_RATE ,CAST((daily_fee*((100-discount_rate)/100))*30 as SIGNED INTEGER) as FEE
# FROM B LEFT JOIN C on B.CAR_TYPE=C.CAR_TYPE

SELECT CAR_ID,B.CAR_TYPE,CAST((daily_fee*30*((100-discount_rate)/100)) as SIGNED INTEGER) as FEE
FROM B LEFT JOIN C on B.CAR_TYPE=C.CAR_TYPE
WHERE 500000<=CAST((daily_fee*30*((100-discount_rate)/100)) as SIGNED INTEGER) and CAST((daily_fee*30*((100-discount_rate)/100)) as SIGNED INTEGER)<2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC