-- 코드를 입력하세요
with A as (
    SELECT FOOD_TYPE,MAX(FAVORITES) as FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)    

SELECT REST_INFO.FOOD_TYPE,REST_ID,REST_NAME,REST_INFO.FAVORITES
FROM REST_INFO, A
WHERE REST_INFO.FOOD_TYPE=A.FOOD_TYPE and REST_INFO.FAVORITES=A.FAVORITES
ORDER BY FOOD_TYPE desc