with A as (
select i.ANIMAL_ID,i.ANIMAL_TYPE,i.NAME #,i.SEX_UPON_INTAKE,o.SEX_UPON_OUTCOME
from ANIMAL_INS i join ANIMAL_OUTS o on i.ANIMAL_ID=o.ANIMAL_ID   
where SEX_UPON_INTAKE!=SEX_UPON_OUTCOME
)

-- 코드를 입력하세요
SELECT *
FROM A