with A as 
(SELECT CAR_ID, ROUND(SUM(DATEDIFF(END_DATE,START_DATE)+1) / COUNT(*),1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY AVERAGE_DURATION desc, CAR_ID desc)

select *
from A
WHERE AVERAGE_DURATION>=7