With A as (
SELECT *
FROM USER_INFO
WHERE YEAR(JOINED)=2021
),
B as (
SELECT DISTINCT COUNT(USER_ID) as total
FROM A
),
C as (
SELECT DISTINCT user_id,YEAR(SALES_DATE) as YEAR,MONTH(SALES_DATE) as MONTH
FROM ONLINE_SALE,B
WHERE ONLINE_SALE.USER_ID in (SELECT USER_ID FROM A)
ORDER BY YEAR,MONTH,USER_ID
)

SELECT YEAR,MONTH,COUNT(*) as PURCHASED_USERS,ROUND(COUNT(*)/B.total,1) as PURCHASED_RATIO
FROM C,B
GROUP BY YEAR,MONTH

# SELECT YEAR(SALES_DATE) as YEAR,MONTH(SALES_DATE) as MONTH,COUNT(DISTINCT ONLINE_SALE.USER_ID) as PURCHASED_USERS,ROUND(COUNT(DISTINCT ONLINE_SALE.USER_ID)/B.total,2) as PUCHASED_RATIO
# FROM ONLINE_SALE LEFT JOIN A on A.USER_ID=ONLINE_SALE.USER_ID,B
# WHERE NOT gender is null
# GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE)
# ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC