-- 코드를 입력하세요
WITH A as (
SELECT ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE, SUM(AMOUNT) as TOTAL
FROM FOOD_ORDER
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
)

SELECT A.PRODUCT_ID, B.PRODUCT_NAME, A.TOTAL* B.PRICE as PRODUCT_TOTAL 
FROM A LEFT JOIN FOOD_PRODUCT as B on A.PRODUCT_ID = B.PRODUCT_ID 
ORDER BY PRODUCT_TOTAL DESC, PRODUCT_ID ASC

# SELECT PRODUCT_ID, PRODUCT_NAME
# FROM FOOD_PRODUCT
