-- 코드를 입력하세요
WITH PRODUCT AS (SELECT PRODUCT_ID,PRODUCT_NAME,PRICE
FROM FOOD_PRODUCT)

# SELECT PRODUCT_ID,PRODUCT_NAME
# FROM FOOD_PRODUCT

SELECT O.PRODUCT_ID, PRODUCT_NAME, P.PRICE*SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O LEFT JOIN PRODUCT P ON O.PRODUCT_ID=P.PRODUCT_ID 
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID