# -- 코드를 입력
# WITH A as (
#     SELECT *
# )

WITH A as (SELECT FLAVOR, SUM(TOTAL_ORDER) as JULY_TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR)

SELECT A.FLAVOR
FROM FIRST_HALF JOIN A on A.FLAVOR=FIRST_HALF.FLAVOR
ORDER BY TOTAL_ORDER+JULY_TOTAL_ORDER DESC LIMIT 3
