# -- 코드를 작성해주세요
with A as (
    SELECT SUM(CODE) as BIT
    FROM SKILLCODES
    WHERE CATEGORY='Front End'
)


SELECT DISTINCT ID,EMAIL,FIRST_NAME,LAST_NAME
FROM DEVELOPERS, A
WHERE DEVELOPERS.SKILL_CODE&A.BIT>0
ORDER BY ID ASC