-- MEMBER_PROFILE와 REST_REVIEW 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회하는 SQL문을 작성해주세요.
-- 회원 이름, 리뷰 텍스트, 리뷰 작성일이 출력
-- 결과는 리뷰 작성일을 기준으로 오름차순, 리뷰 작성일이 같다면 리뷰 텍스트를 기준으로 오름차순
with A as (
    SELECT MEMBER_NAME,REST_REVIEW.MEMBER_ID, COUNT(*) OVER(PARTITION BY MEMBER_ID) as REVIEW_COUNT #,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE, COUNT(*) OVER(PARTITION BY MEMBER_ID) as REVIEW_COUNT
    FROM REST_REVIEW left join MEMBER_PROFILE on REST_REVIEW.MEMBER_ID=MEMBER_PROFILE.MEMBER_ID
    ORDER BY REVIEW_COUNT desc,MEMBER_NAME desc
    LIMIT 1
    
)

SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW join A on A.MEMBER_ID=REST_REVIEW.MEMBER_ID
WHERE MEMBER_NAME is not null
ORDER BY REVIEW_DATE asc, REVIEW_TEXT asc

# SELECT (SELECT MEMBER_NAME FROM MEMBER_PROFILE GROUP BY REVIEW),	REVIEW_TEXT, REVIEW_DATE
# FROM 
